// integration-examples/frontend-angular/src/app/app.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { TOOL_NAMES } from '@carto/maps-ai-tools';
import { MapView } from './components/map-view/map-view';
import { ChatUi } from './components/chat-ui/chat-ui';
import { ZoomControls } from './components/zoom-controls/zoom-controls';
import { LayerToggle } from './components/layer-toggle/layer-toggle';
import { SnackbarComponent } from './components/snackbar/snackbar';
import { MapAIToolsService } from './services/map-ai-tools.service';
import { MapToolsService } from './services/map-tools.service';
import { MapToolsStateService } from './services/map-tools-state.service';
import { ViewState } from './services/deck-map.service';
import {
  Message,
  MapInstances,
  LoaderState,
  LayerConfig,
  SnackbarConfig,
} from './models/message.model';

const WS_URL = 'ws://localhost:3000/ws';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [MapView, ChatUi, ZoomControls, LayerToggle, SnackbarComponent],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App implements OnInit, OnDestroy {
  // State
  messages: Message[] = [];
  isConnected: boolean = false;
  loaderState: LoaderState = null;
  zoomLevel: number = 4;
  layers: LayerConfig[] = [];
  snackbar: SnackbarConfig = { message: null, type: 'error' };

  private mapInstances: MapInstances | null = null;
  private subscriptions: Subscription[] = [];

  constructor(
    private aiToolsService: MapAIToolsService,
    private mapToolsService: MapToolsService,
    private stateService: MapToolsStateService
  ) {}

  ngOnInit(): void {
    // Connect to WebSocket via MapAIToolsService
    this.aiToolsService.connect(WS_URL);

    // Subscribe to state observables
    this.subscriptions.push(
      this.aiToolsService.isConnected$.subscribe((c) => (this.isConnected = c)),
      this.aiToolsService.messages$.subscribe((m) => (this.messages = m)),
      this.aiToolsService.loaderState$.subscribe((s) => (this.loaderState = s)),
      this.aiToolsService.error$.subscribe((err) => this.showSnackbar(err)),
      this.stateService.layers$.subscribe((l) => (this.layers = l))
    );
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach((s) => s.unsubscribe());
  }

  handleMapInit(instances: MapInstances): void {
    this.mapInstances = instances;
    this.mapToolsService.initialize(instances.deck, instances.map);

    // Register layer in state service
    this.stateService.registerLayer({
      id: 'points-layer',
      name: 'Airports',
      color: '#c80050',
      visible: true,
    });
  }

  handleViewStateChange(viewState: ViewState): void {
    this.zoomLevel = viewState.zoom;
  }

  handleSendMessage(content: string): void {
    this.aiToolsService.sendMessage(content);
  }

  async handleZoomIn(): Promise<void> {
    if (this.mapToolsService.isInitialized()) {
      await this.mapToolsService.execute(TOOL_NAMES.ZOOM_MAP, { direction: 'in', levels: 1 });
    }
  }

  async handleZoomOut(): Promise<void> {
    if (this.mapToolsService.isInitialized()) {
      await this.mapToolsService.execute(TOOL_NAMES.ZOOM_MAP, { direction: 'out', levels: 1 });
    }
  }

  async handleLayerToggle(event: { layerId: string; visible: boolean }): Promise<void> {
    if (this.mapToolsService.isInitialized()) {
      const result = await this.mapToolsService.execute(TOOL_NAMES.TOGGLE_LAYER, {
        layerName: event.layerId,
        visible: event.visible,
      });

      // Update state service on success
      if (result.success) {
        this.stateService.setLayerVisibility(event.layerId, event.visible);
      }
    }
  }

  showSnackbar(message: string, type: 'error' | 'info' = 'error'): void {
    this.snackbar = { message, type };
  }

  hideSnackbar(): void {
    this.snackbar = { message: null, type: 'error' };
  }

  get controlsDisabled(): boolean {
    return !this.isConnected || !this.mapInstances;
  }
}

// integration-examples/frontend-react/src/App.jsx
import { useState, useCallback, useEffect } from 'react';
import { MapView } from './components/MapView';
import { ChatUI } from './components/ChatUI';
import { ZoomControls } from './components/ZoomControls';
import { LayerToggle } from './components/LayerToggle';
import { Snackbar } from './components/Snackbar';
import { TOOL_NAMES } from '@carto/maps-ai-tools';
import { useMapTools } from './contexts/MapToolsContext';
import { useMapAITools, useMapAIToolsHttp } from './hooks';
import { USE_HTTP, WS_URL, HTTP_API_URL } from './config/constants';
import './styles/main.css';

// Select hook at module level to respect React rules of hooks
const useAITools = USE_HTTP ? useMapAIToolsHttp : useMapAITools;

/**
 * Main App component
 * Orchestrates map, chat, and tool execution using useMapAITools hook
 */
function App() {
  // State
  const [mapInstances, setMapInstances] = useState(null);
  const [zoomLevel, setZoomLevel] = useState(1.5);
  const [snackbar, setSnackbar] = useState({ message: null, type: 'error' });

  // Context for persistent tool state
  const mapTools = useMapTools();

  // Snackbar helpers
  const showSnackbar = useCallback((message, type = 'error') => {
    setSnackbar({ message, type });
  }, []);

  const hideSnackbar = useCallback(() => {
    setSnackbar({ message: null, type: 'error' });
  }, []);

  // Consolidated hook for AI tools integration
  // Uses HTTP or WebSocket based on USE_HTTP configuration
  const {
    isConnected,
    messages,
    loaderState,
    sendMessage,
    executors,
  } = useAITools({
    ...(USE_HTTP ? { apiUrl: HTTP_API_URL } : { wsUrl: WS_URL }),
    mapInstances,
    mapTools,
    onError: showSnackbar,
  });

  // Register layer in context when map is initialized
  useEffect(() => {
    if (mapInstances) {
      mapTools.registerLayer({
        id: 'points-layer',
        name: 'Airports',
        color: '#c80050',
        visible: true,
      });
    }
  }, [mapInstances, mapTools]);

  // Handle view state changes (for zoom tracking)
  const handleViewStateChange = useCallback((viewState) => {
    setZoomLevel(viewState.zoom);
  }, []);

  // Handle zoom buttons using executors
  const handleZoomIn = useCallback(() => {
    if (executors[TOOL_NAMES.ZOOM_MAP]) {
      const result = executors[TOOL_NAMES.ZOOM_MAP]({ direction: 'in', levels: 1 });
      console.log('Zoom in:', result.message);
    }
  }, [executors]);

  const handleZoomOut = useCallback(() => {
    if (executors[TOOL_NAMES.ZOOM_MAP]) {
      const result = executors[TOOL_NAMES.ZOOM_MAP]({ direction: 'out', levels: 1 });
      console.log('Zoom out:', result.message);
    }
  }, [executors]);

  // Handle layer toggle
  const handleLayerToggle = useCallback(
    (layerId, visible) => {
      if (executors[TOOL_NAMES.TOGGLE_LAYER]) {
        const result = executors[TOOL_NAMES.TOGGLE_LAYER]({ layerName: layerId, visible });
        console.log('Layer toggle:', result.message);
      }
    },
    [executors]
  );

  return (
    <div style={{ display: 'flex', width: '100vw', height: '100vh' }}>
      <div style={{ flex: 1, position: 'relative' }}>
        <MapView onMapInit={setMapInstances} onViewStateChange={handleViewStateChange} />
        {/* Layer Toggle - top left */}
        <div style={{ position: 'absolute', top: 10, left: 10, zIndex: 100 }}>
          <LayerToggle
            disabled={!isConnected || !mapInstances}
            layers={mapTools.getLayers()}
            onToggle={handleLayerToggle}
          />
        </div>
        {/* Zoom Controls - bottom left */}
        <div style={{ position: 'absolute', bottom: 30, left: 10, zIndex: 100 }}>
          <ZoomControls
            disabled={!isConnected || !mapInstances}
            zoomLevel={zoomLevel}
            onZoomIn={handleZoomIn}
            onZoomOut={handleZoomOut}
          />
        </div>
      </div>
      <ChatUI
        isConnected={isConnected}
        onSendMessage={sendMessage}
        messages={messages}
        loaderState={loaderState}
      />
      <Snackbar
        message={snackbar.message}
        type={snackbar.type}
        onClose={hideSnackbar}
        duration={5000}
      />
    </div>
  );
}

export default App;
