// frontend-integration/react/src/App.tsx
import { useState, useCallback } from 'react';
import { MapView } from './components/MapView';
import { ChatUI } from './components/ChatUI';
import { ZoomControls } from './components/ZoomControls';
import { LayerToggle } from './components/LayerToggle';
import { Snackbar } from './components/Snackbar';
import { useMapAITools } from './hooks/useMapAITools';
import { useDeckState } from './hooks/useDeckState';
import { useIsMobile } from './hooks/useIsMobile';
import type { SnackbarConfig } from './types/models';
import './App.css';

export default function App() {
  const deckState = useDeckState();
  const aiTools = useMapAITools();
  const isMobile = useIsMobile();

  const [zoomLevel, setZoomLevel] = useState(3);
  const [sidebarState, setSidebarState] = useState<
    'closed' | 'open' | 'collapsed' | 'half' | 'full'
  >('closed');
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [snackbar, setSnackbar] = useState<SnackbarConfig>({ message: null, type: 'error' });

  const handleViewStateChange = useCallback((viewState: { zoom: number }) => {
    setZoomLevel(viewState.zoom);
  }, []);

  const handleSendMessage = useCallback(
    (content: string) => {
      aiTools.sendMessage(content);
    },
    [aiTools]
  );

  const handleClearChat = useCallback(
    (clearLayers: boolean) => {
      aiTools.clearMessages();
      if (clearLayers) {
        deckState.clearChatGeneratedLayers();
      }
    },
    [aiTools, deckState]
  );

  const handleZoomIn = useCallback(() => {
    const currentView = deckState.getViewState();
    const newZoom = Math.min(22, (currentView.zoom ?? 3) + 1);
    deckState.setInitialViewState({
      latitude: currentView.latitude,
      longitude: currentView.longitude,
      zoom: newZoom,
      pitch: currentView.pitch ?? 0,
      bearing: currentView.bearing ?? 0,
    });
  }, [deckState]);

  const handleZoomOut = useCallback(() => {
    const currentView = deckState.getViewState();
    const newZoom = Math.max(0, (currentView.zoom ?? 3) - 1);
    deckState.setInitialViewState({
      latitude: currentView.latitude,
      longitude: currentView.longitude,
      zoom: newZoom,
      pitch: currentView.pitch ?? 0,
      bearing: currentView.bearing ?? 0,
    });
  }, [deckState]);

  const handleLayerToggle = useCallback(
    (event: { layerId: string; visible: boolean }) => {
      const currentLayers = deckState.getDeckSpec().layers;
      const updatedLayers = currentLayers.map((layer) => {
        if (layer['id'] === event.layerId) {
          return { ...layer, visible: event.visible };
        }
        return layer;
      });
      deckState.setLayers(updatedLayers);
    },
    [deckState]
  );

  const handleLayerFlyTo = useCallback(
    (event: { layerId: string }) => {
      const layer = aiTools.layers.find((l) => l.id === event.layerId);
      if (!layer?.center) return;

      deckState.setInitialViewState({
        latitude: layer.center.latitude,
        longitude: layer.center.longitude,
        zoom: layer.center.zoom ?? 12,
        pitch: 0,
        bearing: 0,
      });
    },
    [deckState, aiTools.layers]
  );

  const handleSidebarStateChange = useCallback(
    (state: 'collapsed' | 'half' | 'full') => {
      setSidebarState(state);
    },
    []
  );

  const toggleSidebar = useCallback(() => {
    if (isMobile) {
      if (sidebarState === 'closed' || sidebarState === 'collapsed') {
        setSidebarState('half');
      } else {
        setSidebarState('closed');
      }
    } else {
      const newOpen = !isSidebarOpen;
      setIsSidebarOpen(newOpen);
      setSidebarState(newOpen ? 'open' : 'closed');
    }
  }, [isMobile, sidebarState, isSidebarOpen]);

  const closeSidebar = useCallback(() => {
    setIsSidebarOpen(false);
    setSidebarState('closed');
  }, []);

  const hideSnackbar = useCallback(() => {
    setSnackbar({ message: null, type: 'error' });
  }, []);

  const isDesktopSidebarOpen = !isMobile && isSidebarOpen;
  const showMobileSidebar = isMobile && sidebarState !== 'closed';
  const sidebarFullOnMobile = isMobile && sidebarState === 'full';

  return (
    <div className="app-container">
      <div className={`main-layout${isDesktopSidebarOpen ? ' sidebar-open' : ''}`}>
        <div className="map-column">
          <header className="app-header">
            <h1 className="app-title">CARTO AI Tools — React</h1>
          </header>

          <div className={`map-container${sidebarFullOnMobile ? ' sidebar-full' : ''}`}>
            <MapView onViewStateChange={handleViewStateChange} />

            <div
              className={`layer-toggle-wrapper${
                showMobileSidebar ? ' below-sidebar' : ''
              }`}
            >
              <LayerToggle
                disabled={!aiTools.isConnected}
                layers={aiTools.layers}
                onToggle={handleLayerToggle}
                onFlyTo={handleLayerFlyTo}
              />
            </div>

            <div className="zoom-controls-wrapper">
              <ZoomControls
                disabled={!aiTools.isConnected}
                zoomLevel={zoomLevel}
                onZoomIn={handleZoomIn}
                onZoomOut={handleZoomOut}
              />
            </div>
          </div>
        </div>

        <div className="sidebar-column">
          {(isDesktopSidebarOpen || showMobileSidebar) && (
            <ChatUI
              isConnected={aiTools.isConnected}
              messages={aiTools.messages}
              loaderState={aiTools.loaderState}
              sidebarState={sidebarState}
              isMobile={isMobile}
              isSidebarOpen={isSidebarOpen}
              onSendMessage={handleSendMessage}
              onSidebarStateChange={handleSidebarStateChange}
              onCloseSidebar={closeSidebar}
              onClearChat={handleClearChat}
            />
          )}
        </div>
      </div>

      {/* FAB button to toggle sidebar */}
      <button
        className={`fab-button${isDesktopSidebarOpen ? ' sidebar-open' : ''}`}
        onClick={toggleSidebar}
        title={isSidebarOpen || showMobileSidebar ? 'Close Chat' : 'Open Chat'}
      >
        {isSidebarOpen || showMobileSidebar ? (
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2">
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        ) : (
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2">
            <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
          </svg>
        )}
      </button>

      {/* Snackbar */}
      <Snackbar config={snackbar} onDismiss={hideSnackbar} />
    </div>
  );
}

// frontend-integration/angular/src/app/app.ts
/**
 * App Component
 *
 * Main application component using JSONConverter-based architecture.
 * Initializes map with CARTO POI layer via DeckState.
 */

import { Component, OnInit, OnDestroy, HostListener } from '@angular/core';
import { Subscription } from 'rxjs';
import { MapView } from './components/map-view/map-view';
import { ChatUi } from './components/chat-ui/chat-ui';
import { ZoomControls } from './components/zoom-controls/zoom-controls';
import { LayerToggle } from './components/layer-toggle/layer-toggle';
import { SnackbarComponent } from './components/snackbar/snackbar';
import { MapAIToolsService } from './services/map-ai-tools.service';
import { DeckMapService, ViewState } from './services/deck-map.service';
import { DeckStateService } from './state/deck-state.service';
import { ConsolidatedExecutorsService } from './services/consolidated-executors.service';
import { TOOL_NAMES } from '@carto/map-ai-tools';
import { environment } from '../environments/environment';
import {
  Message,
  MapInstances,
  LoaderState,
  LayerConfig,
  SnackbarConfig,
} from './models/message.model';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [MapView, ChatUi, ZoomControls, LayerToggle, SnackbarComponent],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App implements OnInit, OnDestroy {
  // State
  messages: Message[] = [];
  isConnected: boolean = false;
  loaderState: LoaderState = null;
  loaderMessage: string = '';
  zoomLevel: number = 3;
  layers: LayerConfig[] = [];
  snackbar: SnackbarConfig = { message: null, type: 'error' };
  sidebarState: 'closed' | 'open' | 'collapsed' | 'half' | 'full' = 'closed';
  isSidebarOpen: boolean = false; // Desktop sidebar state

  private mapInstances: MapInstances | null = null;
  private subscriptions: Subscription[] = [];
  private isMobileViewport: boolean = false;

  constructor(
    private aiToolsService: MapAIToolsService,
    private deckMapService: DeckMapService,
    private deckState: DeckStateService,
    private executorsService: ConsolidatedExecutorsService
  ) {}

  ngOnInit(): void {
    // Check initial viewport size
    this.checkViewportSize();

    // Connect to WebSocket
    this.aiToolsService.connect();

    // Subscribe to state observables
    this.subscriptions.push(
      this.aiToolsService.isConnected$.subscribe((c) => (this.isConnected = c)),
      this.aiToolsService.messages$.subscribe((m) => (this.messages = m)),
      this.aiToolsService.loaderState$.subscribe((s) => (this.loaderState = s)),
      this.aiToolsService.loaderMessage$.subscribe((m) => (this.loaderMessage = m)),
      this.aiToolsService.error$.subscribe((err) => this.showSnackbar(err)),
      this.aiToolsService.layers$.subscribe((l) => (this.layers = l))
    );
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach((s) => s.unsubscribe());
    this.deckMapService.destroy();
  }

  handleMapInit(instances: MapInstances): void {
    this.mapInstances = instances;
    console.log('[App] Map initialized');

    // Force redraw after init
    this.deckMapService.redraw();
  }

  handleViewStateChange(viewState: ViewState): void {
    this.zoomLevel = viewState.zoom;
  }

  handleSendMessage(content: string): void {
    this.aiToolsService.sendMessage(content);
  }

  handleClearChat(clearLayers: boolean = false): void {
    this.aiToolsService.clearMessages();
    if (clearLayers) {
      this.deckState.clearChatGeneratedLayers();
    }
  }

  async handleZoomIn(): Promise<void> {
    const currentView = this.deckState.getViewState();
    const newZoom = Math.min(22, (currentView.zoom ?? 3) + 1);

    await this.executorsService.execute(TOOL_NAMES.SET_DECK_STATE, {
      initialViewState: {
        latitude: currentView.latitude,
        longitude: currentView.longitude,
        zoom: newZoom,
        pitch: currentView.pitch ?? 0,
        bearing: currentView.bearing ?? 0
      }
    });
  }

  async handleZoomOut(): Promise<void> {
    const currentView = this.deckState.getViewState();
    const newZoom = Math.max(0, (currentView.zoom ?? 3) - 1);

    await this.executorsService.execute(TOOL_NAMES.SET_DECK_STATE, {
      initialViewState: {
        latitude: currentView.latitude,
        longitude: currentView.longitude,
        zoom: newZoom,
        pitch: currentView.pitch ?? 0,
        bearing: currentView.bearing ?? 0
      }
    });
  }

  async handleLayerToggle(event: { layerId: string; visible: boolean }): Promise<void> {
    // Update layer visibility in DeckState
    const currentLayers = this.deckState.getLayers();
    const updatedLayers = currentLayers.map(layer => {
      if (layer['id'] === event.layerId) {
        return { ...layer, visible: event.visible };
      }
      return layer;
    });

    this.deckState.setLayers(updatedLayers);
    console.log(`[App] Layer "${event.layerId}" visibility set to ${event.visible}`);
  }

  handleLayerFlyTo(event: { layerId: string }): void {
    // Get layer config with center
    const layer = this.layers.find(l => l.id === event.layerId);
    if (!layer?.center) {
      console.warn('[App] No center coordinates for layer:', event.layerId);
      return;
    }

    // Directly set initialViewState WITHOUT adding a pin
    // Pins should only be added when user requests a location via chat
    this.deckState.setInitialViewState({
      latitude: layer.center.latitude,
      longitude: layer.center.longitude,
      zoom: layer.center.zoom ?? 12,
      pitch: 0,
      bearing: 0,
    });

    console.log(`[App] Flying to layer "${event.layerId}":`, layer.center);
  }

  showSnackbar(message: string, type: 'error' | 'info' | 'success' = 'error'): void {
    this.snackbar = { message, type };
  }

  hideSnackbar(): void {
    this.snackbar = { message: null, type: 'error' };
  }

  get controlsDisabled(): boolean {
    return !this.isConnected || !this.mapInstances;
  }

  @HostListener('window:resize', ['$event'])
  onResize(): void {
    this.checkViewportSize();
  }

  checkViewportSize(): void {
    const wasMobile = this.isMobileViewport;
    this.isMobileViewport = window.innerWidth <= 768;

    // Handle state transitions between mobile and desktop
    if (wasMobile && !this.isMobileViewport) {
      // Switched to desktop: convert mobile state to desktop state
      if (this.sidebarState === 'collapsed' || this.sidebarState === 'half' || this.sidebarState === 'full') {
        this.isSidebarOpen = false;
        this.sidebarState = 'closed';
      }
    } else if (!wasMobile && this.isMobileViewport) {
      // Switched to mobile: convert desktop state to mobile state
      if (this.sidebarState === 'closed') {
        this.sidebarState = 'half';
      }
    }
  }

  isMobile(): boolean {
    return this.isMobileViewport;
  }

  handleSidebarStateChange(state: 'collapsed' | 'half' | 'full'): void {
    this.sidebarState = state;
  }

  toggleSidebar(): void {
    if (this.isMobileViewport) {
      // Mobile: toggle between half and closed
      if (this.sidebarState === 'closed' || this.sidebarState === 'collapsed') {
        this.sidebarState = 'half';
      } else {
        this.sidebarState = 'closed';
      }
    } else {
      // Desktop: toggle open/closed
      this.isSidebarOpen = !this.isSidebarOpen;
      this.sidebarState = this.isSidebarOpen ? 'open' : 'closed';
    }
  }

  get isDesktopSidebarOpen(): boolean {
    return !this.isMobileViewport && this.isSidebarOpen;
  }
}
